networks:
  default:
    name: dev-bridge
    external: true

x-web: &x-web # <<: *x-env
  build:
    context: .
    dockerfile: Dockerfile
  restart: on-failure
  tty: true

services:
  php:
    container_name: bueld-checkout-php
    build:
      context: ./docker/dev/php
      dockerfile: Dockerfile
    volumes:
      - .:/data
      - ./documents:/data/documents

  web:
    <<: *x-web
    container_name: bueld-checkout-web
    volumes_from:
      - php
    ports:
      - ${WEB_PORT}:80
    command: ["nginx"]
    depends_on:
      - php

  # Development server for fast updates.
  node:
    # build:
    #   context: .
    #   dockerfile: docker/dev/node/Dockerfile
    image: node:latest
    working_dir: /data
    volumes_from:
      - php
    # command: npm run dev
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: "development"
      WATCHPACK_POLLING: "true"
      NODE_BUNDLE_ENTRY_FILE: ${NODE_BUNDLE_ENTRY_FILE}
      NODE_BUNDLE_OUTPUT_PATH: ${NODE_BUNDLE_OUTPUT_PATH}
      NODE_BUNDLE_OUTPUT_FILENAME: ${NODE_BUNDLE_OUTPUT_FILENAME}
      NODE_BUNDLE_OUTPUT_PUBLIC_PATH: ${NODE_BUNDLE_OUTPUT_PUBLIC_PATH}
      NODE_DEVSERVER_HOST: ${NODE_DEVSERVER_HOST}
      NODE_DEVSERVER_PORT: ${NODE_DEVSERVER_PORT}
      NODE_DEVSERVER_STATIC: ${NODE_DEVSERVER_STATIC}
      NODE_DEVSERVER_PROXY_ROOT: ${NODE_DEVSERVER_PROXY_ROOT}
    depends_on:
      - php
    restart: always
    ports:
      - "${NODE_DEVSERVER_PORT}:${NODE_DEVSERVER_PORT}"
