volumes:
  bueld-mysql-data:
  # bueld-redis-data:

networks:
  default:
    name: bueld
    # external: true

x-web: &x-web # <<: *x-env
  image: ryoukan:3010/bueld/checkout/web:latest
  restart: on-failure
  tty: true

services:
  php:
    container_name: php
    image: ryoukan:3010/bueld/checkout/php:latest
    volumes:
      - .:/data
      - ./documents:/data/documents

  web:
    <<: *x-web
    container_name: web
    volumes_from:
      - php
    ports:
      - ${WEB_PORT}:80
    command: ["nginx"]
    depends_on:
      - php

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: >
      --max_connections=${MYSQL_MAX_CONNECTIONS}
      --sql_mode=${MYSQL_SQL_MODE}
      --autocommit=${MYSQL_AUTOCOMMIT}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_MAX_CONNECTIONS: ${MYSQL_MAX_CONNECTIONS}
    expose:
      - ${MYSQL_PORT}
    volumes:
      - bueld-mysql-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_PORT: ${PMA_PORT}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      MAX_EXECUTION_TIME: ${PMA_MAX_EXECUTION_TIME}
    ports:
      - ${PMA_PORT}:80

  # redis:
  #   image: redis/redis-stack:latest
  #   environment:
  #     - REDIS_ARGS=--requirepass ${REDIS_PASSWORD} --save 20 1
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - bueld-redis-data:/var/lib/redis-data
