CREATE TABLE employees (
  id INT NOT NULL AUTO_INCREMENT,
  initial_id INT NULL,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,

  deleted_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  created_at TIMESTAMP NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
